config:
  install_tree: ~/SPACK_HOME/install_home/bbpviz/install
  module_roots:
    tcl: ~/SPACK_HOME/install_home/bbpviz/tcl
    lmod: ~/SPACK_HOME/install_home/bbpviz/lmod
  build_stage:
    - $tempdir
    - $spack/var/spack/stage
  install_path_scheme: '${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:8}'
